Jropp/jason-ropp-js-iobp

edit-user.html, main.css, new-user.html, user-profile.html, users-list.html
A question regarding page titles. Materials recommended including the page title, site title, and company title in the header. But I couldn't find an example of how to format that in the code anywhere.
=> HTML user files added and styled

users-list.html
To resolve #16
1. Added event arguments to user-cards in users-list.com
2. Added toggleUserDetails function to script
=> Updated user card display toggle in users-list.html

README.md, src/user-component/user-component.html, src/user-list/user-list.html
This cleans up the html of the form in order to make sure the form is conducive to screen readers and  functions smoothly across browsers.
Previously form items used placeholders to label input fields. This has now been replaced with `<label for="inputId">TypeOfInput:</label>`
Closes #44 
Create user, delete user, save edited user.
This does not solve the problem of empty field warnings in #46 
=> Onboarding Project: Form Accessibility Standards

README.md, src/api/user-database.js, src/api/utils.js, src/user-component/user-component.html, src/user-list/user-list.html
Properly formats user name entry.
Continues the work on validating information from issue #55 
I added a `titleCaseName` function to the database api that ensures proper phone format on entry and display.
Closes #55 
Enter a name with variations of caps and lower case. It should display properly as 'Last, First' in user list when you hit save. 
Does not account for any names that need caps outside of the first letter. My apologies to the Irish.
=> Onboarding Project: Validate name

src/user-component/user-component.html, src/user-list/user-list.html
- This adds hover effects to most of the button properties
- This adds a div around the (no-users) message to make it look cleaner
- This changes the background to the autofill input boxes, so it doesn't turn yellow
=> Editing Hover effects, style of (no-users) message, and autofill background

README.md, src/user-component/user-component.css, src/user-component/user-component.html, src/user-list/user-list.html
To tweak the styling of the card to match JHA designs. 
[JHA Design Specifications](https://jha-design.herokuapp.com/components/card/) suggest certain spacing, font-size and what not. 
The specs call for using semantic `header` and `footer` elements in the layout of `cards`. Issue #91 covers the specifics of that layout. 
Closes #91 
- Create, delete, and edit user cards. 
- Try to find ways to break it by entering bad email or number formats, leaving fields blank. 
- Try to create warning messages then delete, or save a new user. 
I'll give you a dollar if you can find a way to break it.
This also deletes a couple unused lines of code and enters a small clarifying comment after I spent 5 minutes trying to figure out why an "unused" property and function was breaking things when I deleted …
=> Onboarding Project: Format Card to Match JHA Design

src/user-list/user-list.html
This gets rid of extraneous code in user–list.
Over the last several PRs I have moved a lot of functionality to user component. As a result a good chunk of the code in user-list was no longer being used. This included the use of modes and CSSDesign in displaying and hiding the create user button, which is no longer in user list.
I deleted any code that was no longer being used.
Create and delete users. Everything should appear and function as you'd expect.
None
=> Onboarding Project: User-List Cleanup

src/api/utils.js, src/user-component/user-component.html
Refactors the phone validation and formatting utility.
While it was functioning properly, there were areas that needed refactoring to make it more readable and maintainable.
- I broke the insert symbols function into a parent function `formatPhoneNumber()`, and two children `insertDomesticSymbols()` and `insertInternationalSymbols()`.
- I tweaked the naming in 'validatePhoneInput()' to make it more readable.
- All page functionality, especially around number validation and formatting should be the same.
```
Phone format:  +xxx (xxx) xxx-xxxx
Email format: xxxxxx@xxxx.*
```
- Any arrangement of symbols and numbers should work so long as there are 10-13 digits. Anything else should display a warning message.
- Look for poor naming or jumbled organization of code. Does the way the …
=> Onboarding Project: Utils Refactor

src/api/user-database.js, src/user-component/user-component.html, src/user-list/user-list.html
Cleans up, simplifies, or renames code where possible to make code more readable. No functionality was changed.
Since the beginning of the project, my ability to write clear code has improved, I thought it worthwhile to go back through the code to apply new learning.
Functions were renamed to better represent their purpose: `deleteAllUsers` instead of `deleteUsers` gives more clarity that this function isn't just batch deleting a set of users, but rather deleting all of the users in the database.
- Create, edit, delete users to ensure functionality was left intact.
- Look through the code and check for instances where:
- naming is unclear
- code should be separated into another function
- variables or steps are unnecessary (no functional value, do not aid readability)
I'm not sure what to …
=> Onboarding Project: Database refactor

src/api/user-database.js
Added database sorting on save as a default
=> Added default last name alphabetization on save.

src/user-list/user-list.html
Adds sort controls to user-list so that users can be ordered by department, last name, or first name
=> Sort Users Mini Project: Added sort controls in user-list

src/index.ejs
Sets the scrollbar to be always on.
Previously when you created enough user-cards to display the scrollbar, it would cause a leftward shift that looked janky. This sets the scrollbar to stay on no matter what.
I implemented this using an `overflow-y: scroll` setting in index.ejs
Create or delete, expand or collapse users beyond the current height of the screen. There should be no small shift when you cross that threshold.
=> Onboarding Project: Styling - Scroll bar

README.md
Runs through readme to get rid of repeated items, unclear wording, or any syntax issues.
- Are things are worded in a concise and clear manner?
- Are all needed elements of the project represented in the README?
None
=> Onboarding Project: Readme

README.md, src/api/user-database.js, src/api/utils.js, src/user-component/user-component.html, src/user-list/user-list.html
I accidentally set the last merge to go into master
=> Revert "Mini Project: Sort Dropdown Menu Styling"

README.md, src/user-list/user-list.html
Styles the sort dropdown menu.
Dropped use of `<select>` dropdown and went with animated `<div>` with `<li>`
#120 
Click the sort menu and sort stuff!
The sort direction dropdown will be coming up the in the next PR
None
=> Dropdown styling

src/user-component/user-component.html
Reverts Jropp/jason-ropp-js-iobp#125
=> Revert "Mini-Project: Phone Symbols Bug"

PULL_REQUEST_TEMPLATE.md, README.md, src/user-list/user-list.html
This adds a second dropdown that allows you to sort in alphabetical or reverse alphabetical order as applied to whatever category is being sorted by.
This was requested by Collin as a part fo the mini-project.
Sort your users by a certain category, then switch the order to reverse alphabetical. They should display properly switching back and forth. 
=> Mini Project: Sort By Direction

package.json, src/api/user-database.js, src/api/utils.js, src/user-component/user-component.html, src/user-list/user-list.html
When there were no users, there was an attempt at a function call to ValidateUsers as soon as you tried to add a new user.
I removed a conditional in `ready()` that was preventing the classes from being loaded in the new user card.
Delete all users, then try to create a new one. The new user should create correctly.
none
=> Code Splitting: Bug Fix – error on no users

src/user-component/user-component.html
Refactor. No functional changes.
- Cleans up code
- Combines class setting functions into one
- Cleans Up CSS
- Combines format messages into single messages property
- Deletes Unused functions like `cancel`
- Leans more heavily on this.isExpanded to reduce interdependence of functions or various tricks to find whether the state is expanded or collapsed
- Create
- Delete
- Expand
- Collapse
- Edit / Delete
- Edit / Save
- Sort Users By
- Change Sort Direction
Try multiple options at random.
Watch for 
- buttons appropriately disabled (when edit open, when info not formatted properly)
- format warnings appear and disappear when appropriate (info entered wrong/corrected. edit open warning.
None
=> Onboarding Project: User-Component.html refactor

README.md, src/api/user-database.js, src/user-component/user-component.html, src/user-list/user-list.html
Get's project back to original functionality after plugging in 
functions into the live database rather than the local database. 
I used the same api calls as before from users-list and user-component. I just retrofitted them in the Database api to make live Database requests.
Works on #145 
- Create, edit, and sort users. Functionality should be the same.
- Popup messages should display when a database action is successfully completed
Remember to delete your browser cache, otherwise the cached files will load and you will not see an updated version of the app.
=> Database Mini-Project: Link To Database

src/api/user-database.js
Refactors code in user-database.js.
Changes to live database have depreciated old code. Also, current code needs changes for clarity.
All functionality should be the same.
Read through and check for instances where naming is unclear or cluttered. 
=> Database-mini: Database API Refactor

src/api/user-database.js, src/user-list/user-list.html
If you search by `department` in reverse alphabetical order, then it _should_ display the users in that department in alphabetical order by `lastName`. If there are matching last names, then they are sorted by `firstName.`
Sorting subgroups by alphabetical order just seems more intuitive to me at this point. The section headers display groups by last name and I would find myself confused by the order of the first names. So I changed it.
In the `compareTwoUsers` function in the database—which sorts two users by any number of categories, each getting less priority than the previous category—I added a reverseSort boolean that checks to see if the sort setting is currently set to reverse, and also whether or not this category should be reversed. Only the primary sort category, which is the …
=> Database Mini: Bug Fix – User Sorting Order

src/user-list/user-list.html
Deletes unused event listener from back in the localStorage database days.
USE YOUR EYES!
Poverty has not been solved by this PR.
=> Database Mini: Delete unused event listener.

src/api/user-database.js, src/user-list/user-list.html
Refactors the code for easier maintainability.
While working through attaching to the live database, things got jumbled, depreciated, etc. 
Unused code deleted, let changed to const where appropriate, and functions re-arranged where appropriate.
Functionality should be unchanged.
Are there any parts that could use more clarity (or less clarity)?
=> Database Mini: Refactor

src/api/user-database.js
There is a const that should be a let.
=> Const to let fix

README.md, src/api/user-database.js, src/user-component/user-component.html, src/user-list/user-list.html
Converts the localStorage database to a live database. 
This is a test of the mini-projects for the interns onboarding project.
- For the most part, the same database api structure was maintained, but tweaked to work with a synchronous database.
Other items that had to be tweaked:
- Sort users had to be reworked and moved into user-database.js
- The user object property names had to be updated for the database schema
Closes #145 
- Does this meet all requirements for live database mini?
- Does all user manipulation sort, create, delete functionality work properly?
=> Live Database Mini Project

src/api/utils.js, src/index.ejs, src/user-component/user-component.html, webpack.config.js
Where relevant it changes let to const
When I started, I didn't know what const was for. Actually I was mostly using var when I started. So this adds const to any variable that is not reassigned value in order to make readability of code better.
Running through all code functionality: sort, create, edit. There should be no const errors.
=> Onboarding Project: Lets changed to Consts

README.md
This goes through the readme to make sure all things are clear and up to date.
=> Onboarding Project: README catch up

src/api/user-database.js
Converts XHR to async/await fetch.
Makes the code cleaner, more readable, and faster.
Functionality should be the same as before
- If sort settings are changed, sort settings should persist and user should sort to appropriate location
Are there remaining issues or things this PR hasn't solved yet? Are there long-term implications?
=> Onboarding Project: Fetch

src/user-list/dropdown-list.html
I missed a property name change in the last PR
=> Bug: Missed property name change

src/api/user-database.js, src/api/utils.js, src/index.js, src/user-component/warning-message.js, src/user-list/user-list.js
Prettier was changing single quotes to double quotes in javascript and I didn't realize it. This changes those back to single quotes where appropriate.
=> Changed Double To Single Quotes

src/api/user-database.js, src/user-component/warning-message.js, src/user-list/user-list.html, src/user-list/user-list.js
Handles bad server response.
While the server was down I realized that there was no handling of bad responses.
To fix this:
- I put an if statement in the get sorted users to catch anything other than a 200 response. 
- I put a message box in a dom-if inside of user-list that displays if users were unable to be loaded.
Open the page when the server is down (or change the server url at the top of the database.js file).
The message should display properly on user list. 
This does not fix bad responses for saving/deleting/editing a new user if it fails (could be put in a toast).
=> Onboarding Project: Handle Server Response

src/api/user-database.js
This changes the url endpoint of the database. 
Users should now load, delete, edit save, save new, etc.
=> Database Endpoint Changed

.gitignore, src/user-list/user-list.html, src/user-list/user-list.js
Minor Change:
- spacing of event listeners
- deleted unneeded arguments in html bound functions
Major Change:
- Refactor of setDisplaySortHeader
Sorting should work as expected
- Delete Users in various sort modes
- Create Users in various sort modes
- Edit Users in various sort modes
Sorting should persist after any changes.
=> Refactor: User List

src/api/user-database.js, src/user-list/user-list.html, src/user-list/user-list.js
Moves sorting as much into database as possible.
Functions and sort array assignments were moved into the database API so now it just takes a primary sort string and a boolean as to whether the sort is reversed or not.
```js
Database.getUsersSortedBy('firstName' ,false);
```
Sort any way you can think of.
Sort then add, edit, or delete a user. Sort should persist through those changes.
=> Sort update

src/api/user-database.js, src/user-component/user-component.js, src/user-list/dropdown-list.html, src/user-list/toast-message.html, src/user-list/user-list.js
Small spacing fixes, bracket placement, and one regex assigned to a variable for clarity.
No functional changes
None
=> Spacing and Bracket Placement Fixes

src/user-component/user-component.js
Dynamically grabs class TITLE CASE using variables to set the class of the userCard.
While trying to simplify the class setting/animating process (mundo failure) I came across this way to clean up the class setting.
Create/Delete User
- Expand the details of a user card, then add or remove a different user. The open display of that expanded user should persist.
Sort/Save Edit
- Do the same thing, but the user should be collapsed (No users should be open).
=> Onboarding Project: Refactor — More Dynamic Class Setting

src/api/user-database.js, src/user-list/user-list.html, src/user-list/user-list.js
- Changes Name of Function
- uses .includes and indexOf to shorten up lines of code
- deletes unused variables
Mostly touches persistent expanded cards. Expand cards and sort in various ways.
Watch for accurate display of category headers (Single letter for first/last name sort, whole word for department sort)
=> Onboarding Project: Refactor — Userlist
