src/user-component/user-component.html

In the save function I replaced this.resetFormState() with this.cancel() so that on save the new user card collapses. 
This was after a convo with Nathan Phillips that the persistent new user card was dominating the page rather than users list.
Create a new user and click save. The new user window should collapse.
None

Collapse New User Card On Save

---

src/user-component/user-component.html
src/user-list/user-list.html

Adds style to the popup message and placement of it on the screen.
Also adds a transition animation to have it fade in/up and out/down.
You can adjust the animation speeds and popup ares in the .message-box and .show-message classes.

styled the popup message and added animation

---

src/user-component/user-component.html

Fixes the display of a user card after delete.
When the dom-repeat refreshes, it recycles previous information to increase load times. Because of this, any class and animation changes made to a card will persist. So this PR changes the styling of 
user display cards to being in the default collapsed state, just before they are deleted.
I changed 
`this.userCardClass = this.classes.COLLAPSE_EXISTING;`
to
`this.userCardClass = this.classes.COLLAPSE_DEFAULT;`
```
delete(e) {
e.preventDefault();
database.deleteUser(this.user);
this.editInProgress(false);
this.mode = this.modes.DISPLAY;
this.userCardClass = this.classes.COLLAPSE_DEFAULT;
this.toggleEditable();
this.clearInputFormatWarningMessages();
}
```
In the CSS I added a set of `.collapse-existing-user-default` classes set to the collapse …

Onboarding Project: Bug Fix - Card styles reset immediately to default after delete

---

src/user-component/user-component.html

There were a series of merge conflicts in PRs yesterday that I had to resolve. This apparently slipped through. It was just leftover tags that was around this.
```js
.create-user-button:hover>jha-add-person-icon {
fill: #0070b7;
}
```
I deleted the tags and tested how the code was functioning.
When you hover over the create user button, it should turn blue.

Fixes unresolved conflict in master

---

src/user-component/user-component.html

This fixes #77 
Dom-repeat recycles information from previous dom-repeated items, so changes persist to other dom-repeated items if you delete one of the dom-repeated items. 
I fixed the problem by adding the toggle icon function to the function called when you delete a user.
```js
delete(e) {
e.preventDefault();
database.deleteUser(this.user);
this.editInProgress(false);
this.mode = this.modes.DISPLAY;
this.userCardClass = this.classes.COLLAPSE_DEFAULT;
**this.toggleUserCardButtonIcon();**
this.toggleEditable();
this.clearInputFormatWarningMessages();
}
```
closes #77 
Create two users (if you don't have any users), expand the top user, delete the top user. The remaining user should display normally. In particular the arrow icon at the bottom of the card should be black and pointing down …

Onboarding Project: Bug Fix – Persistent Collapse User Detail Arrow Icon

---

src/user-component/user-component.html

Fixes the bug that made you have to click the expand user details button twice before it would work.
Previous fixes were to the state of the user card and the icons in it. Round one was #75 and round two was PR #82. 
This rounds those changes out by: 
- changing how the card init works (previously it called `toggleUserCardCollapse`)
```js
if (this.user.id) {
this.toggleEditable();
this.userCardClass = this.classes.COLLAPSE_EXISTING;
}
```
- setting the toggle functions to check for the EXPANDED_DEFAULT state that gets set to a card on delete (and persists to other remaining cards in the dom-repeat template because of information recycling feature of dom-repeat).
```js
let collapsed = (cardClass === this.classes.COLLAPSE_DEFAULT || cardClass === this.classes.COLLAPSE_EXISTING); …
```

Onboarding Project: Bug Fix – Expanding User Card Requires 2 Clicks After A Delete 

---

src/user-component/user-component.html

There were spacing issues in the open edit card, in part because former display of the edit card had a "Edit: First Last" format. 
So I re-added a dom-if template that took care of this. Minor styling to that header solved the spacing issue in the existing user card.
Open an edit on a user. It should display the "Edit: First Last" properly and in a pleasing manner that reminds you of those feels you get standing by a fire on a summer evening.
**Check in Firefox.** 
I am getting some wonky display issues, but I also got issues that @collincahill didn't get in his firefox browser. Please let me know if you are or are not seeing issues there. 
In my Firefox browser, the buttons end up outside of the user card.
None

Onboarding Project: User Card Spacing Fix.

---

src/user-component/user-component.html

When you would open an edit user card, it properly displayed Edit: Last, First, but because of data binding to the input form, the header would change along with the input form before actually clicking the save button.
I changed data bound data to a data bound function that returned the proper format for the current user. Since it is bound to a change in `user` it only updates on load or save.
```
<h1 class="edit-user-header">[[setEditUserHeader(user)]]</h1>
```
Fixes #89 
Create a user. Edit that users name, the `Edit: Last, First` should not change to what you've put into the input until you click save.
None

Bug-Fix: User Name Header Shouldn't Change Till Save

---

src/user-component/user-component.css
src/user-component/user-component.html
src/user-list/user-list.html

This changes the color, size, and tone of the warning messages.
Also, it breaks the rules and ALSO fixes card content expanding out of the card when a warning message pops up.
This is a change to reflect JHA's style specifications for [voice](https://jha-design.herokuapp.com/style/voice/) and [color](https://jha-design.herokuapp.com/style/color/). In the meantime I found a bug.
I changed the messages to be more human, and changed them from 'red' to jha's red. 
Closes #92 
- Create two user cards (if you don't already have two). 
- Edit one of the users so that the phone and email are not properly formatted.
- Delete that user.
- The remaining user should collapse, display, and expand normally.
Discovered a bug that new user entry persists after clicking cancel. 
Under penalty of public …

Onboard Project: Bug-Fix Warning messages

---

README.md
src/user-component/user-component.html
src/user-list/user-list.html

This adds `CREATE_MODE` to the user-component and refactors dom-ifs and other functions to use CREATE_MODE rather than various `&&` or `||` statements to figure out the state.
There have for a long time been three states of user-component:
- Create New
- Display Existing
- Edit Existing
But prior to this PR the Create New state was typically found by using something like `let isNewUserCard = !this.user.id` as user.id was only a part of existing users.
To implement:
- I added CREATE_NEW to my modes property.
- I moved the setting of the initial card state inside the user component. The initial state is now set by whether or not a user is passed to the user-component. If it is, then the card starts collapsed in display mode. If not, then the card starts as a collapsed create new user card. …

Onboarding Project: Added CREATE_MODE

---

README.md
src/user-component/user-component.html
src/user-list/user-list.html

When the screen width is too small the text of the popup message would overflow. This sets the width to a static 250px rather than by percentage. It also changes the style of the toast message box a bit to match the current color scheme.
Create, delete, or save an edit on a new user at various screen widths. The popup message should display properly.

Onboarding Project: Bug Fix - Toast Sizing Causes Text To Overflow

---

src/user-component/user-component.html

This and only this:
```
jha-person-icon {
position: relative;
left: 14px;
}
```
jha-person-icon beside first name input should display inline with other icons.

Onboarding Project: User Name Icon Style Fix

---

src/api/user-database.js
src/api/utils.js
src/user-component/user-component.html
src/user-list/user-list.html

Adds a utility function that dynamically gets any number of filter parameters, prioritizes them by order entered, then filters users based on those priorities.
This is a mini project add on. Previously, user-list did not have a way to add filters.
I Added a `SortUtil` class in `utils.js`. This dynamically grabs inputted filters, then dynamically sorts users through those inputted filters.
In this instance, if all three were passed in it would order users by first name, then if any first names matched it would order those by Department, if there was again a match it would order those by last name:
```
SortUtils.filterUsersBy(users, FIRST_NAME, [DEPARTMENT, LAST_NAME]);
```
This allows any number of future filters to be passed without changing much code. As long as the filter argument is a …

Sort Name Mini Project: Name Sort Utility

---

src/user-list/user-list.html

Adds visual alphabetization for sorted categories. When sorting departments, it actually displays the departments as well.
The problem with sorting departments or first names is that it takes a hot second to adjust to the new sort. First names are visible, but the first name sort is not immediately intuitive because of the Last, First display order. Departments are not even shown in the collapsed state of cards. 
I added a dom-if template to each dom-repeated user card that is only displayed if it is the first card in a new sorted category. So if the users name is Bob and the previous user was Annie, then the header will be displayed there.
The letter displayed is set dynamically by grabbing the first letter of the sorted category. So if you are sorting first names, and Bob is the first …

Sort Name Mini Project: Sorting Display Styles

---

src/user-component/user-component.html

Squashes bug that caused extra symbols to be inserted into phone numbers on each sort.
It was a bug, it looked ugly.
A quick regex check to see if the user already had phone symbols before trying to insert them.
Sort users multiple times, users phone numbers should still be formatted correctly.

Mini-Project: Phone Symbols Bug

---

PULL_REQUEST_TEMPLATE.md
src/api/user-database.js
src/api/utils.js
src/user-list/user-list.html

This moves all the sorting of users into `Database.getUsersSortedBy()` in the database API
I hit a wall with getting the dom-repeat to refresh. Bryan Coulter suggested moving the sorting into the Database, both to solve the problem, and for cleaner code and more flexibility for later use of the Database.
- Sort functions are in Database API
- user-list.html now gets sorted users rather than sorting users itself.
- Sort users by each category
- Sort by alphabetical direction
- Set sort parameters and create or edit a new user (should be placed in proper sort category)
- Create or edit a user into a category that doesn't exist (should show header for that new category immediately)
There are some issues with the expanded/collapsed display of user cards that are being worked on in another …

Sort Users Mini Project: Refactor – Move Sort to Database API

---

src/user-list/user-list.html

Expanded user cards now collapse on Edit-Save and Sort. 
Random expanded cards moving around in the list when sorted in different ways was a little janky. 
This does still keep user cards expanded when you delete a user or save a new user.
I created a `resetExpandedCardIds(bool)` function that either clears out the userIds array or prompts the function that triggers the `<user-component is-expanded=[[isUserCardDisplayExpanded]]`> attribute.
This closes #128 
Expand a users details then:
These actions should not collapse the card:
- Save New User
- Delete User 
These actions should collapse the card:
- Save User Edit
- Sort users or change sort direction
There is a bug in firefox that user details are displayed as editable inputs that you can put a cursor in. It doesn't let you edit but …

Sort Users Mini Project: Collapse Cards On Edit-Save and Sort

---

src/user-component/user-component.css

Adds css selector specifically for Firefox readonly
User details should appear without bottom border.
Firefox still allows a cursor to be displayed when input is clicked. I don't know whether to fix this or not.
None

Sort Users Mini: Firefox readonly Bug Fix

---

package.json
src/api/user-database.js
src/api/utils.js
src/user-component/user-component.html
src/user-list/user-list.html

This lazy loads ValidateUtils and Database classes during `ready()` lifecycle event.
After taking a deeper dive into webpack and discovering code splitting, I thought it might be fun to incorporate it into my project.
The path to get to require.ensure() started with webpack's dynamic import: `import(pathToFile)` which wasn't playing nice (possibly with polymer-webpack-loader.) Though I did get `import()` to work on a polymer 3 element. 
Then I found an earlier version of `import`, require.ensure(). This creates a separate hashed bundle of code during the webpack build that gets added when the code hits the require.ensure(). 
There were some tweaks I had to make to ensure ValidateUtil and Database don't get called before they are loaded, so there is some refactoring, but no user …

Intern Onboarding Project: User Component Code Splitting

---

src/user-list/user-list.html

Restores the persistent display of an expanded user card after a new card is created or an existing card is deleted.
This used to be functionality in the project that got disconnected during the course of adding the database.
- The dom-if function call was set to send user.id instead of the new user._id.
- I modified onUsersLoaded to check for `edit` in an incoming message from the `usersLoaded` event. If that's the case then it resets the user card ids. 
1. Open the details on one user card then:
- Create a new user
- Delete an existing user
in both of these cases the details you expanded should remain visible.
2. Open the details on one user card then:
- Save an edit on a user
- Change the sort or sort direction in some way.
in both of these cases the details you expanded should now be …

Database Mini: Persistent Display

---

src/api/user-database.js
src/user-component/user-component.html
src/user-list/user-list.html

Causes an animated collapse on an existing user when the card is deleted.
During the course of adding the live database, the former way of dealing with recycling issues in a dom-repeat list no longer worked. Although the persistent display of expanded id cards was fixed in #155 , when an existing user was deleted it stayed expanded and just sat there for a while then suddenly disappeared. It looked janky.
Entirely solved by adding one line to the delete function inside the user-component:
```js
this.toggledetailsVisibility();
```
Delete a user, it should pleasantly collapse before disappearing.

Database Mini: Collapse On Delete

---

src/api/user-database.js

Updates the getUserById database call to work with the live database.
Part of the requirements for the project was to have a getUsersById call, though it was never required to actually use it in the project. This connects that function to the database and exposes it to the rest of the project through a new dispatched event.
I created a new xhr GET request that sends the user id and sends the response item to `this.sendUserById()`, which dispatches an event.
```js
static getUserById(userId) {
const requestUrl = `http://iop-db.herokuapp.com/users/${userId}`;
const xhr = new XMLHttpRequest();
xhr.open('GET', requestUrl, true);
xhr.setRequestHeader("Content-Type", "application/json");
xhr.send();
xhr.onreadystatechange = responseText => {
if (xhr.readyState === 4 && xhr.status === 200) { …
```

Database Mini: Connect getUserById

---

README.md
build-tools/webpack.production.js
webpack.config.js

It moves the ` new WorkboxPlugin.GenerateSW()` to webpack.production.js
The service worker was hindering development as it was in the normal webpack config. Every time the code was updated the cache had to be cleared in the browser for testing.
I moved the appropriate plugin and required files into webpack.production.js
`$Yarn build` should generate a service worker in the dist folder.
Running the server (if you've cleared the cache) should not show workbox caching files.
There is an error being thrown because index is still looking for the service worker. I don't know if this is something that needs to be fixed (sort of like the webcomponent shims that error out).

Onboarding-Project: Service Worker Moved To Production Config

---

src/user-component/user-component.js

Fixes bug that pressing enter bypasses proper form validation.
A form checker was added to the save function.
Improperly format email or phone number, then press enter. The warning message should be displayed and the save should not go through properly.
Are there remaining issues or things this PR hasn't solved yet? Are there long-term implications?

Bug Fix: Enter Key Bypasses Form Validation

---

src/user-list/dropdown-list.html
src/user-list/user-list.html
src/user-list/user-list.js

Moves dropdown menus into a custom component that is reused for sort categories and sort direction
A large percentage of the HTML and CSS in user-list came from the dropdown menus. This cuts down that code by moving it into a separate file.
```html
<dropdown-list selected-item><dropdown-list>
```
The selectedItem property exposes the item you've selected to the parent. The selectedItem property also controls which item has a check mark next to it to note it being selected.
Sort and such. Functionality should be the same as before.

Onboarding Project: dropdown-list Custom Component

---

src/api/user-database.js
src/design/css/shared-styles.html
src/user-list/toast-message.html
src/user-list/user-list.html
src/user-list/user-list.js

Moves toast functionality and styling into its own custom component
As the project has grown and picked up more features, maintaining all of those items in two components started getting hectic.
The toast-message custom element takes in a message through its message property. When that message changes, the animation for the toast is fired.
Add a user, delete a user, edit a user

Onboarding Project: Toast Messages Component

---

src/user-list/toast-message.html

Deletes unused properties and explicitly states addPersonIcon property (which was implicitly created in popupMessage before.
No functionality change. Just deletions and additions.
None

Refactor: Toast Message

---

src/user-list/toast-message.html
src/user-list/user-list.js

Resets the toast message to handle a repeated message.
If you edit/save the exact same user two times in a row, it send the exact same message to the toast-message component and the observer doesn't fire. This resets that message to the toast to bypass this issue.
```js
if (response.message) {
const toastReset = '';
this.toastMessage = toastReset;
this.toastMessage = response.message;
}
```
Edit then save the exact same user twice in a row (without changing their first or last name). The toast message should still appear that you've edited that user twice.
Are there remaining issues or things this PR hasn't solved yet? Are there long-term implications?

Bug Fix: Toast repeat

---

src/user-component/user-component.html
src/user-component/user-component.js

Changes editUser header to be data bound text rather than data-bound function
Eliminates three lines of javascript.
Expanding card should display Edit: Users, Name as before.

Got rid of editUserHeader function

---

src/index.ejs
src/user-component/user-component.js
src/user-list/user-list.html
src/user-list/user-list.js

Suggestions from Collin: 
- Change app title to User List
- In connectedCallback(), all the event listeners could be put into a single function and called in connectedCallback()
- `cancel` event could be called `cancelEdit` or something, for clarity
- `editInProgress` could be renamed to `editStarted` or something more specific. `editInProgress` sounds more like something you'd name a boolean than an event.
- Naming of `noUsersHeaderMessage` not consistent with the content
Functionality should be the same as usual. 
None

Collin Nits for user-list.js

---

src/user-list/user-list.js

Changes the display change on an edit save of an existing user. 
Previously this collapsed ALL cards when there was an edit save. This causes all cards to persist whatever state they were in (Except for the edit save, which is collapsed).
Open the details of a few users. Edit a user and change all information. Save the changes. All expanded users should still be expanded.

Onboard Project: got rid of collapse on edit/save

---

src/user-list/user-list.js

Takes the boolean argument out of resetExpandedCardIds. 
Previously I used a boolean call for a case where I would or wouldn't want the ids reset from another function, but it was silly to put that as an argument rather than an if statement. 
Now resetExpandedCardIds just resets the id array whenever it's called
Sort users. Expanded cards should collapse.

Onboarding Project: Refactor – Reset Expanded Ids 

---

src/api/utils.js
src/user-list/user-list.js

Moves phone settings (number length range, symbols, etc) into TITLE_CASE settings object.
The various settings for phone numbers were spattered across the code. This change makes it easier to change settings in one spot, thus making the code more maintainable.
Provide instructions on how to test this change. If there are tricky or edge cases that should be tested, mention those too.
Screenshots are great for highlighting visual changes.
Are there remaining issues or things this PR hasn't solved yet? Are there long-term implications?

Onboarding Project: Refactor — Utils

---

src/api/user-database.js
src/user-list/dropdown-list.html
src/user-list/user-list.html
src/user-list/user-list.js

This disables the dropdown sort feature when a user edit is in progress.
Colin caught a bug that when you sort while a user edit is in progress, it locks the user card in a collapsed edit mode.
I added a 'disabled/enabled' rel to the dropdown sort and targeted that with CSS to show when the dropdown is disabled.
I also added an if(!editInProgress) statement at the beginning of both sort functions to block in the event that someone tries to click the dropdown menus anyway.
Open an edit, try to sort. 
Save the edit, try to sort.

Onboarding Project: Bux Fix — Disable Sort When Edit Is Open
